version: "3.7"
services:
    app:
        build:
            args:
                user: tiendapp
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: catalogue
        container_name: catalogue-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - catalogue

    db:
        image: mysql:5.7
        container_name: catalogue-db
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - catalogue

    nginx:
        image: nginx:alpine
        container_name: catalogue-nginx
        restart: always
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - catalogue

networks:
    catalogue:
        driver: bridge
